import { BaseSeeder } from '@adonisjs/lucid/seeders'

const seed = [
  {
    label: '123 Baby',
    value: '123-baby',
    selected: false,
    quantity: 1,
  },
  {
    label: '18',
    value: '18',
    selected: false,
    quantity: 6,
  },
  {
    label: '3 Corações',
    value: '3-coracoes',
    selected: false,
    quantity: 13,
  },
  {
    label: '51',
    value: '51',
    selected: false,
    quantity: 8,
  },
  {
    label: '8KM',
    value: '8km',
    selected: false,
    quantity: 11,
  },
  {
    label: 'A Tal da Castanha',
    value: 'a-tal-da-castanha',
    selected: false,
    quantity: 14,
  },
  {
    label: 'Aboca',
    value: 'aboca',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Abrigitte',
    value: 'abrigitte',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Absolut',
    value: 'absolut',
    selected: false,
    quantity: 8,
  },
  {
    label: 'Acqua Lia',
    value: 'acqua-lia',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Acqua Panna',
    value: 'acqua-panna',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Acqualia',
    value: 'acqualia',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Acquasantiera',
    value: 'acquasantiera',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Adegamãe',
    value: 'adegamae',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ades',
    value: 'ades',
    selected: false,
    quantity: 11,
  },
  {
    label: 'Adobe',
    value: 'adobe',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Água da Pedra',
    value: 'agua-da-pedra',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Ahmad Tea London',
    value: 'ahmad-tea-london',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Aime Boucher',
    value: 'aime-boucher',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Alabastro',
    value: 'alabastro',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Alamos',
    value: 'alamos',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Albai',
    value: 'albai',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Alfredo Roca',
    value: 'alfredo-roca',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Aliança',
    value: 'alianca',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Allumé',
    value: 'allume',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Alma Negra',
    value: 'alma-negra',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Almadén',
    value: 'almaden',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Almena Del Sur',
    value: 'almena-del-sur',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Almond Breeze',
    value: 'almond-breeze',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Alpino',
    value: 'alpino',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Altue',
    value: 'altue',
    selected: false,
    quantity: 1,
  },
  {
    label: "Amaretto Dell'Orso",
    value: 'amaretto-dell-orso',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Amarula',
    value: 'amarula',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Amazoo',
    value: 'amazoo',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Amázzoni',
    value: 'amazzoni',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Ambev',
    value: 'ambev',
    selected: false,
    quantity: 2,
  },
  {
    label: 'American',
    value: 'american',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Amigos da Vida',
    value: 'amigos-da-vida',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Amstel',
    value: 'amstel',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Angelica Zapata',
    value: 'angelica-zapata',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Antarctica',
    value: 'antarctica',
    selected: false,
    quantity: 54,
  },
  {
    label: 'Aperol',
    value: 'aperol',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Apogee',
    value: 'apogee',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Aptanutri',
    value: 'aptanutri',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Aqua Coco',
    value: 'aqua-coco',
    selected: false,
    quantity: 2,
  },
  {
    label: 'As3',
    value: 'as3',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ateliê',
    value: 'atelie',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Aurora',
    value: 'aurora',
    selected: false,
    quantity: 21,
  },
  {
    label: 'Ayni',
    value: 'ayni',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bacalhoa',
    value: 'bacalhoa',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bacardi',
    value: 'bacardi',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Bad Boy',
    value: 'bad-boy',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Baden Baden',
    value: 'baden-baden',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Baileys',
    value: 'baileys',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Baileys Irish Cream',
    value: 'baileys-irish-cream',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Ballantines',
    value: 'ballantines',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Baly',
    value: 'baly',
    selected: false,
    quantity: 13,
  },
  {
    label: 'Batavo',
    value: 'batavo',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bavaria',
    value: 'bavaria',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Beats',
    value: 'beats',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Becks',
    value: 'becks',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Becosa',
    value: 'becosa',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Beefeater',
    value: 'beefeater',
    selected: false,
    quantity: 8,
  },
  {
    label: 'Bela Ischia',
    value: 'bela-ischia',
    selected: false,
    quantity: 1,
  },
  {
    label: "Bell's",
    value: 'bell-s',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bicicleta',
    value: 'bicicleta',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bio Natural Life',
    value: 'bio-natural-life',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bioleve',
    value: 'bioleve',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Black & White',
    value: 'black---white',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Black Flip',
    value: 'black-flip',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Black Princess',
    value: 'black-princess',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Blizzard',
    value: 'blizzard',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Blue Diamond',
    value: 'blue-diamond',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Blue Moon',
    value: 'blue-moon',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bodega Lagarde',
    value: 'bodega-lagarde',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bolla',
    value: 'bolla',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bombay Sapphire',
    value: 'bombay-sapphire',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Br Spices',
    value: 'br-spices',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Brahma',
    value: 'brahma',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Breeze',
    value: 'breeze',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Buchanans',
    value: 'buchanans',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Budweiser',
    value: 'budweiser',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Buffalo Trace',
    value: 'buffalo-trace',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Bulldog',
    value: 'bulldog',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Busca Vida',
    value: 'busca-vida',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Cabaré',
    value: 'cabare',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Cachaça da Roça',
    value: 'cachaca-da-roca',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Cacildis',
    value: 'cacildis',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Café do Centro',
    value: 'cafe-do-centro',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Calem',
    value: 'calem',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Callia',
    value: 'callia',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Campari',
    value: 'campari',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Caninha da Roça',
    value: 'caninha-da-roca',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Canto da Flora',
    value: 'canto-da-flora',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Carmelina',
    value: 'carmelina',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Carmen Insigne',
    value: 'carmen-insigne',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Carmim',
    value: 'carmim',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Carrefour',
    value: 'carrefour',
    selected: false,
    quantity: 74,
  },
  {
    label: 'Carrefour Classic',
    value: 'carrefour-classic',
    selected: false,
    quantity: 8,
  },
  {
    label: 'Casa Crebar',
    value: 'casa-crebar',
    selected: false,
    quantity: 12,
  },
  {
    label: 'Casa de Bento',
    value: 'casa-de-bento',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Casa Dei Fanti',
    value: 'casa-dei-fanti',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Casa Ermelinda Freitas',
    value: 'casa-ermelinda-freitas',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Casa Ferreirinha',
    value: 'casa-ferreirinha',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Casa Perini',
    value: 'casa-perini',
    selected: false,
    quantity: 11,
  },
  {
    label: 'Casa Valduga',
    value: 'casa-valduga',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Casal Garcia',
    value: 'casal-garcia',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Casal Mendes',
    value: 'casal-mendes',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Casillero Del Diablo',
    value: 'casillero-del-diablo',
    selected: false,
    quantity: 16,
  },
  {
    label: 'Castillo de Albai',
    value: 'castillo-de-albai',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Catena',
    value: 'catena',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Cella',
    value: 'cella',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Cereser',
    value: 'cereser',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Chá Leão',
    value: 'cha-leao',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Chalise',
    value: 'chalise',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Chandon',
    value: 'chandon',
    selected: false,
    quantity: 15,
  },
  {
    label: 'Charles de Lissandre',
    value: 'charles-de-lissandre',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Chás Real',
    value: 'chas-real',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Château Brejou',
    value: 'chateau-brejou',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Chemin Des Sables',
    value: 'chemin-des-sables',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Chianti',
    value: 'chianti',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Chivas Regal',
    value: 'chivas-regal',
    selected: false,
    quantity: 8,
  },
  {
    label: 'Chuva de Prata',
    value: 'chuva-de-prata',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Cidade Imperial',
    value: 'cidade-imperial',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Cinzano',
    value: 'cinzano',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Citrus',
    value: 'citrus',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Clashd',
    value: 'clashd',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Clight',
    value: 'clight',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Coca-Cola',
    value: 'coca-cola',
    selected: false,
    quantity: 42,
  },
  {
    label: 'Cointreau',
    value: 'cointreau',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Colorado',
    value: 'colorado',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Concha y Toro',
    value: 'concha-y-toro',
    selected: false,
    quantity: 9,
  },
  {
    label: 'Conde de Cortes',
    value: 'conde-de-cortes',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Cono Sur',
    value: 'cono-sur',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Contini',
    value: 'contini',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Corona',
    value: 'corona',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Corvo',
    value: 'corvo',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Country Wine',
    value: 'country-wine',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Crystal',
    value: 'crystal',
    selected: false,
    quantity: 8,
  },
  {
    label: 'Crystal Sparkling',
    value: 'crystal-sparkling',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Cynar',
    value: 'cynar',
    selected: false,
    quantity: 1,
  },
  {
    label: 'D Autrefois',
    value: 'd-autrefois',
    selected: false,
    quantity: 1,
  },
  {
    label: 'D.v Catena',
    value: 'd-v-catena',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Da Fruta',
    value: 'da-fruta',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Dabarca',
    value: 'dabarca',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Dafruta',
    value: 'dafruta',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Danone',
    value: 'danone',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Dante Robino',
    value: 'dante-robino',
    selected: false,
    quantity: 6,
  },
  {
    label: 'De Marchi',
    value: 'de-marchi',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Del Valle',
    value: 'del-valle',
    selected: false,
    quantity: 35,
  },
  {
    label: 'Dewars',
    value: 'dewars',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Di Bartolo',
    value: 'di-bartolo',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Dikoko',
    value: 'dikoko',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Doce Veneno',
    value: 'doce-veneno',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Dom Bosco',
    value: 'dom-bosco',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Domecq',
    value: 'domecq',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Don Julio',
    value: 'don-julio',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Doña Paula',
    value: 'dona-paula',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Draco',
    value: 'draco',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Draft',
    value: 'draft',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Drambuie',
    value: 'drambuie',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Dreher',
    value: 'dreher',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ducoco',
    value: 'ducoco',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Easy Booze',
    value: 'easy-booze',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Easy Drinks',
    value: 'easy-drinks',
    selected: false,
    quantity: 14,
  },
  {
    label: 'Eisenbahn',
    value: 'eisenbahn',
    selected: false,
    quantity: 14,
  },
  {
    label: 'El Jimador',
    value: 'el-jimador',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ellegance',
    value: 'ellegance',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Emiliana',
    value: 'emiliana',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Espírito de Minas',
    value: 'espirito-de-minas',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Espiritu de Chile',
    value: 'espiritu-de-chile',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Estrella Galicia',
    value: 'estrella-galicia',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Evian',
    value: 'evian',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Evolutto',
    value: 'evolutto',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Exclusivo Carrefour',
    value: 'exclusivo-carrefour',
    selected: false,
    quantity: 9,
  },
  {
    label: 'Faisão',
    value: 'faisao',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Fanta',
    value: 'fanta',
    selected: false,
    quantity: 19,
  },
  {
    label: 'Faustino',
    value: 'faustino',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Fausto',
    value: 'fausto',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ferraspari',
    value: 'ferraspari',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Finca Los Trenzones',
    value: 'finca-los-trenzones',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Foral',
    value: 'foral',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Fords',
    value: 'fords',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Fração Única',
    value: 'fracao-unica',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Frangélico',
    value: 'frangelico',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Freixenet',
    value: 'freixenet',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Frescca',
    value: 'frescca',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Fresh',
    value: 'fresh',
    selected: false,
    quantity: 9,
  },
  {
    label: 'Frisco',
    value: 'frisco',
    selected: false,
    quantity: 18,
  },
  {
    label: 'Frontera',
    value: 'frontera',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Frontera Merlot',
    value: 'frontera-merlot',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Frutah',
    value: 'frutah',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Frutilac',
    value: 'frutilac',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Fusion',
    value: 'fusion',
    selected: false,
    quantity: 3,
  },
  {
    label: 'FYs',
    value: 'fys',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Garibaldi',
    value: 'garibaldi',
    selected: false,
    quantity: 22,
  },
  {
    label: 'Gato Negro',
    value: 'gato-negro',
    selected: false,
    quantity: 8,
  },
  {
    label: 'Gatorade',
    value: 'gatorade',
    selected: false,
    quantity: 11,
  },
  {
    label: 'Gaúcho',
    value: 'gaucho',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Gazela',
    value: 'gazela',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Gekkeikan',
    value: 'gekkeikan',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Góes',
    value: 'goes',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Goose Island',
    value: 'goose-island',
    selected: false,
    quantity: 3,
  },
  {
    label: "Gordon's",
    value: 'gordon-s',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Gordons',
    value: 'gordons',
    selected: false,
    quantity: 9,
  },
  {
    label: 'Gran Viña',
    value: 'gran-vina',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Granja União',
    value: 'granja-uniao',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Grão Vasco',
    value: 'grao-vasco',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Grey Goose',
    value: 'grey-goose',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Guaraviton',
    value: 'guaraviton',
    selected: false,
    quantity: 1,
  },
  {
    label: 'H2OH!',
    value: 'h2oh-',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Heilige',
    value: 'heilige',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Heineken',
    value: 'heineken',
    selected: false,
    quantity: 12,
  },
  {
    label: 'Hendricks',
    value: 'hendricks',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Henkell Freixenet',
    value: 'henkell-freixenet',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Hocus Pocus',
    value: 'hocus-pocus',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Horchata',
    value: 'horchata',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Howler Head',
    value: 'howler-head',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Hungry Jack',
    value: 'hungry-jack',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Il Roccolo',
    value: 'il-roccolo',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Império',
    value: 'imperio',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Indaiá',
    value: 'indaia',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Intencion',
    value: 'intencion',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Isla Grande',
    value: 'isla-grande',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Itaipava',
    value: 'itaipava',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Italac',
    value: 'italac',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Itambé',
    value: 'itambe',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Itubaína',
    value: 'itubaina',
    selected: false,
    quantity: 2,
  },
  {
    label: "Jack Daniel's",
    value: 'jack-daniel-s',
    selected: false,
    quantity: 9,
  },
  {
    label: 'Jamava',
    value: 'jamava',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Jambucana',
    value: 'jambucana',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Jameson',
    value: 'jameson',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Jardim',
    value: 'jardim',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Johnnie Walker',
    value: 'johnnie-walker',
    selected: false,
    quantity: 22,
  },
  {
    label: 'Jose Cuervo',
    value: 'jose-cuervo',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Jota Pe',
    value: 'jota-pe',
    selected: false,
    quantity: 3,
  },
  {
    label: 'JP Azeitão',
    value: 'jp-azeitao',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Jungle',
    value: 'jungle',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Juxx',
    value: 'juxx',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Kaiser',
    value: 'kaiser',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Kaly',
    value: 'kaly',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Kawaii',
    value: 'kawaii',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Kenko',
    value: 'kenko',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ketel One',
    value: 'ketel-one',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Kressmann',
    value: 'kressmann',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Kuat',
    value: 'kuat',
    selected: false,
    quantity: 2,
  },
  {
    label: "La Cave d'Augustin Florent",
    value: 'la-cave-d-augustin-florent',
    selected: false,
    quantity: 2,
  },
  {
    label: 'La Francette',
    value: 'la-francette',
    selected: false,
    quantity: 1,
  },
  {
    label: 'La Moneda',
    value: 'la-moneda',
    selected: false,
    quantity: 6,
  },
  {
    label: 'La Vanguardia',
    value: 'la-vanguardia',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Labrot e Graham',
    value: 'labrot-e-graham',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Lagunitas',
    value: 'lagunitas',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Lambrusco',
    value: 'lambrusco',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Lancers',
    value: 'lancers',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Larios',
    value: 'larios',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Le Rosé de Julie',
    value: 'le-rose-de-julie',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Leão',
    value: 'leao',
    selected: false,
    quantity: 13,
  },
  {
    label: 'Leatt',
    value: 'leatt',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Leco',
    value: 'leco',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Leonoff',
    value: 'leonoff',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Licor 43',
    value: 'licor-43',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Life Mix',
    value: 'life-mix',
    selected: false,
    quantity: 12,
  },
  {
    label: 'Lillet',
    value: 'lillet',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Lindoya',
    value: 'lindoya',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Lipton',
    value: 'lipton',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Liquid',
    value: 'liquid',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Lor',
    value: 'lor',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Lua Nova',
    value: 'lua-nova',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Lübeck',
    value: 'lubeck',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Lucarelli',
    value: 'lucarelli',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Luminus Life',
    value: 'luminus-life',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Macieira',
    value: 'macieira',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Maguary',
    value: 'maguary',
    selected: false,
    quantity: 31,
  },
  {
    label: 'Mais Coco',
    value: 'mais-coco',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Malbec',
    value: 'malbec',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Malibu',
    value: 'malibu',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Manto Blanco',
    value: 'manto-blanco',
    selected: false,
    quantity: 16,
  },
  {
    label: 'Maratá',
    value: 'marata',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Marc',
    value: 'marc',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Marcel Martin',
    value: 'marcel-martin',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Marcus James',
    value: 'marcus-james',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Maria Guarda',
    value: 'maria-guarda',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Marques de Casa Concha',
    value: 'marques-de-casa-concha',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Martini',
    value: 'martini',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Mate Real',
    value: 'mate-real',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Mateus',
    value: 'mateus',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Mathieu Teisseire',
    value: 'mathieu-teisseire',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Matte Leão',
    value: 'matte-leao',
    selected: false,
    quantity: 9,
  },
  {
    label: 'Meia Lua',
    value: 'meia-lua',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Melitta',
    value: 'melitta',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Mena Kaho',
    value: 'mena-kaho',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Mendel Wines',
    value: 'mendel-wines',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Merlot',
    value: 'merlot',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Michelob',
    value: 'michelob',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Mid',
    value: 'mid',
    selected: false,
    quantity: 4,
  },
  {
    label: "Mike's",
    value: 'mike-s',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Mikes Hard Lemonade',
    value: 'mikes-hard-lemonade',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Minalba',
    value: 'minalba',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Miolo',
    value: 'miolo',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Mioranza',
    value: 'mioranza',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Moema',
    value: 'moema',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Monsaraz',
    value: 'monsaraz',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Monster',
    value: 'monster',
    selected: false,
    quantity: 20,
  },
  {
    label: 'Monte da Ribeira',
    value: 'monte-da-ribeira',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Monte Sur',
    value: 'monte-sur',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Montesur',
    value: 'montesur',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Montilla',
    value: 'montilla',
    selected: false,
    quantity: 2,
  },
  {
    label: "Moscato D'Asti",
    value: 'moscato-d-asti',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Mouton Cadet',
    value: 'mouton-cadet',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Mu',
    value: 'mu',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Não Informado',
    value: 'nao-informado',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Natale Verga',
    value: 'natale-verga',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Native',
    value: 'native',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Natural One',
    value: 'natural-one',
    selected: false,
    quantity: 23,
  },
  {
    label: "Nature's Heart",
    value: 'nature-s-heart',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Naturelle',
    value: 'naturelle',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Natures Heart',
    value: 'natures-heart',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Nescafé',
    value: 'nescafe',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Nescau',
    value: 'nescau',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Nesquik',
    value: 'nesquik',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Nestlé',
    value: 'nestle',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Nestlé Pureza Vital',
    value: 'nestle-pureza-vital',
    selected: false,
    quantity: 3,
  },
  {
    label: 'No Brand',
    value: 'no-brand',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Norton',
    value: 'norton',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Not Milk',
    value: 'not-milk',
    selected: false,
    quantity: 1,
  },
  {
    label: 'NotCo',
    value: 'notco',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Novas',
    value: 'novas',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Novecento',
    value: 'novecento',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Nude',
    value: 'nude',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Nutren',
    value: 'nutren',
    selected: false,
    quantity: 3,
  },
  {
    label: 'O Jornaleiro',
    value: 'o-jornaleiro',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Old Bridge',
    value: 'old-bridge',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Old Parr',
    value: 'old-parr',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Old Red',
    value: 'old-red',
    selected: false,
    quantity: 1,
  },
  {
    label: 'OQ',
    value: 'oq',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Original',
    value: 'original',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Orloff',
    value: 'orloff',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Osborne',
    value: 'osborne',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ovomaltine',
    value: 'ovomaltine',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Panul',
    value: 'panul',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Papa Figos',
    value: 'papa-figos',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Paramana',
    value: 'paramana',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Pardal Telhado',
    value: 'pardal-telhado',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Parmalat',
    value: 'parmalat',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Passport',
    value: 'passport',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Passport Scotch',
    value: 'passport-scotch',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Pata Negra',
    value: 'pata-negra',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Patagônia',
    value: 'patagonia',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Peachtree',
    value: 'peachtree',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Pedra 90',
    value: 'pedra-90',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Península',
    value: 'peninsula',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Penumbra',
    value: 'penumbra',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Pepsi',
    value: 'pepsi',
    selected: false,
    quantity: 15,
  },
  {
    label: 'Pequenas Partilhas',
    value: 'pequenas-partilhas',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Perdigão',
    value: 'perdigao',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Pérgola',
    value: 'pergola',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Periquita',
    value: 'periquita',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Petra',
    value: 'petra',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Piemonte Barbera',
    value: 'piemonte-barbera',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Pilão',
    value: 'pilao',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Piracanjuba',
    value: 'piracanjuba',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Piscine',
    value: 'piscine',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Pitters',
    value: 'pitters',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Plaza del Torres',
    value: 'plaza-del-torres',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Poder da Terra',
    value: 'poder-da-terra',
    selected: false,
    quantity: 12,
  },
  {
    label: 'Possible',
    value: 'possible',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Powerade',
    value: 'powerade',
    selected: false,
    quantity: 6,
  },
  {
    label: "Prat's",
    value: 'prat-s',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Prata',
    value: 'prata',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Prats',
    value: 'prats',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Praya',
    value: 'praya',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Precioso',
    value: 'precioso',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Pressade',
    value: 'pressade',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Primitivo',
    value: 'primitivo',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Puente de Piedra',
    value: 'puente-de-piedra',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Puente Sur',
    value: 'puente-sur',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Punta Negra',
    value: 'punta-negra',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Quinta Jubair',
    value: 'quinta-jubair',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Real Grei',
    value: 'real-grei',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Red Bull',
    value: 'red-bull',
    selected: false,
    quantity: 14,
  },
  {
    label: 'Red Puro',
    value: 'red-puro',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Reguengos',
    value: 'reguengos',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Relax',
    value: 'relax',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Renato Ratti',
    value: 'renato-ratti',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Risovita',
    value: 'risovita',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Roca',
    value: 'roca',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Roda',
    value: 'roda',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Roleta Russa',
    value: 'roleta-russa',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Royale',
    value: 'royale',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ruffino',
    value: 'ruffino',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Rutini',
    value: 'rutini',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ryuujin',
    value: 'ryuujin',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Sadia',
    value: 'sadia',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Sagatiba',
    value: 'sagatiba',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Saint Germain',
    value: 'saint-germain',
    selected: false,
    quantity: 17,
  },
  {
    label: 'Salina',
    value: 'salina',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Salton',
    value: 'salton',
    selected: false,
    quantity: 16,
  },
  {
    label: 'Salvatore Longobardo',
    value: 'salvatore-longobardo',
    selected: false,
    quantity: 1,
  },
  {
    label: 'San Pellegrino',
    value: 'san-pellegrino',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Sangue de Boi',
    value: 'sangue-de-boi',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Santa Carolina',
    value: 'santa-carolina',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Santa Colheita',
    value: 'santa-colheita',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Santa Helena',
    value: 'santa-helena',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Santa Julia',
    value: 'santa-julia',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Santa Rita',
    value: 'santa-rita',
    selected: false,
    quantity: 5,
  },
  {
    label: 'São Lourenço',
    value: 'sao-lourenco',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Schin',
    value: 'schin',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Schweppes',
    value: 'schweppes',
    selected: false,
    quantity: 17,
  },
  {
    label: 'Seagate',
    value: 'seagate',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Seagrams',
    value: 'seagrams',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Sette Spezie',
    value: 'sette-spezie',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Sferrie',
    value: 'sferrie',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Siegel Single Vineyard',
    value: 'siegel-single-vineyard',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Siete Soles',
    value: 'siete-soles',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Singleton',
    value: 'singleton',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Skol',
    value: 'skol',
    selected: false,
    quantity: 15,
  },
  {
    label: 'Skyy',
    value: 'skyy',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Smartwater',
    value: 'smartwater',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Smirnoff',
    value: 'smirnoff',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Sococo',
    value: 'sococo',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Sol',
    value: 'sol',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Spaten',
    value: 'spaten',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Sprite',
    value: 'sprite',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Starbucks',
    value: 'starbucks',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Stella Artois',
    value: 'stella-artois',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Stock',
    value: 'stock',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Suave',
    value: 'suave',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Sukita',
    value: 'sukita',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Supra Soy',
    value: 'supra-soy',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Swift',
    value: 'swift',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Tamaron',
    value: 'tamaron',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Tang',
    value: 'tang',
    selected: false,
    quantity: 13,
  },
  {
    label: 'Tanqueray',
    value: 'tanqueray',
    selected: false,
    quantity: 15,
  },
  {
    label: 'Tempos de Góes',
    value: 'tempos-de-goes',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Tequimex',
    value: 'tequimex',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Terra Brazilis',
    value: 'terra-brazilis',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Terra Nova',
    value: 'terra-nova',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Terranostra',
    value: 'terranostra',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Terrazas de Los Andes',
    value: 'terrazas-de-los-andes',
    selected: false,
    quantity: 2,
  },
  {
    label: 'TERROIR DU MONDE',
    value: 'terroir-du-monde',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Terroirs Du Monde',
    value: 'terroirs-du-monde',
    selected: false,
    quantity: 16,
  },
  {
    label: 'The Glenlivet',
    value: 'the-glenlivet',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Therezópolis',
    value: 'therezopolis',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Thikará',
    value: 'thikara',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Tial',
    value: 'tial',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Tiger',
    value: 'tiger',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Toddynho',
    value: 'toddynho',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Todeschini',
    value: 'todeschini',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Tônica Antarctica',
    value: 'tonica-antarctica',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Toro Bianco',
    value: 'toro-bianco',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Torquay',
    value: 'torquay',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Tosti',
    value: 'tosti',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Trapiche',
    value: 'trapiche',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Trivento',
    value: 'trivento',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Tropical',
    value: 'tropical',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Tropisuco',
    value: 'tropisuco',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Twinings',
    value: 'twinings',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Ultra',
    value: 'ultra',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Valdouro',
    value: 'valdouro',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Velho Barreiro',
    value: 'velho-barreiro',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Veuve Clicquot',
    value: 'veuve-clicquot',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Vida Veg',
    value: 'vida-veg',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Villa Massa',
    value: 'villa-massa',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Villa Piva',
    value: 'villa-piva',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Viña Losar',
    value: 'vina-losar',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Viña Valdivieso',
    value: 'vina-valdivieso',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Viñas del Mar',
    value: 'vinas-del-mar',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Vinecol',
    value: 'vinecol',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Viñedos Marchigue',
    value: 'vinedos-marchigue',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Vinha da Casinha',
    value: 'vinha-da-casinha',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Vinicola Salton',
    value: 'vinicola-salton',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Vino di Bartolo',
    value: 'vino-di-bartolo',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Vitória Régia',
    value: 'vitoria-regia',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Vivant',
    value: 'vivant',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Viver',
    value: 'viver',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Voss',
    value: 'voss',
    selected: false,
    quantity: 1,
  },
  {
    label: 'White Horse',
    value: 'white-horse',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Woodbridge',
    value: 'woodbridge',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Wyborowa',
    value: 'wyborowa',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Xandô',
    value: 'xando',
    selected: false,
    quantity: 13,
  },
  {
    label: 'Yaguara',
    value: 'yaguara',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Yai',
    value: 'yai',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Yakult',
    value: 'yakult',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Yara',
    value: 'yara',
    selected: false,
    quantity: 1,
  },
  {
    label: 'YoPRO',
    value: 'yopro',
    selected: false,
    quantity: 5,
  },
  {
    label: 'Yummy',
    value: 'yummy',
    selected: false,
    quantity: 9,
  },
  {
    label: 'YVY',
    value: 'yvy',
    selected: false,
    quantity: 2,
  },
  {
    label: 'Zaccagnini',
    value: 'zaccagnini',
    selected: false,
    quantity: 1,
  },
]

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method
  }
}
