import { BaseSeeder } from '@adonisjs/lucid/seeders'

const data = [
  {
    label: 'Água com gás',
    value: 'agua-com-gas',
    selected: false,
    quantity: 16,
  },
  {
    label: 'Água de Coco',
    value: 'agua-de-coco',
    selected: false,
    quantity: 20,
  },
  {
    label: 'Água Saborizada',
    value: 'agua-saborizada',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Água sem gás',
    value: 'agua-sem-gas',
    selected: false,
    quantity: 38,
  },
  {
    label: 'Água Tônica',
    value: 'agua-tonica',
    selected: false,
    quantity: 15,
  },
  {
    label: 'Amendôas',
    value: 'amendoas',
    selected: false,
    quantity: 8,
  },
  {
    label: 'Aperitivos',
    value: 'aperitivos',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Arroz',
    value: 'arroz',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Aveia',
    value: 'aveia',
    selected: false,
    quantity: 17,
  },
  {
    label: 'Brasil',
    value: 'brasil',
    selected: false,
    quantity: 29,
  },
  {
    label: 'Cachaça',
    value: 'cachaca',
    selected: false,
    quantity: 29,
  },
  {
    label: 'Cafés Gelados',
    value: 'cafes-gelados',
    selected: false,
    quantity: 19,
  },
  {
    label: 'Castanha',
    value: 'castanha',
    selected: false,
    quantity: 18,
  },
  {
    label: 'Cervejas Especiais',
    value: 'cervejas-especiais',
    selected: false,
    quantity: 53,
  },
  {
    label: 'Cervejas Tradicionais',
    value: 'cervejas-tradicionais',
    selected: false,
    quantity: 86,
  },
  {
    label: 'Chá Pronto',
    value: 'cha-pronto',
    selected: false,
    quantity: 31,
  },
  {
    label: 'Conhaque',
    value: 'conhaque',
    selected: false,
    quantity: 6,
  },
  {
    label: 'Coqueteis',
    value: 'coqueteis',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Drinks Prontos',
    value: 'drinks-prontos',
    selected: false,
    quantity: 32,
  },
  {
    label: 'Energéticos',
    value: 'energeticos',
    selected: false,
    quantity: 58,
  },
  {
    label: 'Ervas',
    value: 'ervas',
    selected: false,
    quantity: 17,
  },
  {
    label: 'Espanha',
    value: 'espanha',
    selected: false,
    quantity: 2,
  },
  {
    label: 'França',
    value: 'franca',
    selected: false,
    quantity: 11,
  },
  {
    label: 'Gin',
    value: 'gin',
    selected: false,
    quantity: 59,
  },
  {
    label: 'Isotônicos',
    value: 'isotonicos',
    selected: false,
    quantity: 17,
  },
  {
    label: 'Kits e Pack de Cerveja',
    value: 'kits-e-pack-de-cerveja',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Licores',
    value: 'licores',
    selected: false,
    quantity: 26,
  },
  {
    label: 'Licorosos',
    value: 'licorosos',
    selected: false,
    quantity: 1,
  },
  {
    label: 'Mate',
    value: 'mate',
    selected: false,
    quantity: 18,
  },
  {
    label: 'Outros  Kits',
    value: 'outros--kits',
    selected: false,
    quantity: 10,
  },
  {
    label: 'Outros Países',
    value: 'outros-paises',
    selected: false,
    quantity: 23,
  },
  {
    label: 'Plantas',
    value: 'plantas',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Refresco em Pó',
    value: 'refresco-em-po',
    selected: false,
    quantity: 55,
  },
  {
    label: 'Rum',
    value: 'rum',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Saquê',
    value: 'saque',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Sem Açúcar',
    value: 'sem-acucar',
    selected: false,
    quantity: 49,
  },
  {
    label: 'Sem Lactose',
    value: 'sem-lactose',
    selected: false,
    quantity: 23,
  },
  {
    label: 'Soja',
    value: 'soja',
    selected: false,
    quantity: 3,
  },
  {
    label: 'Suco Concentrado',
    value: 'suco-concentrado',
    selected: false,
    quantity: 14,
  },
  {
    label: 'Suco de Soja',
    value: 'suco-de-soja',
    selected: false,
    quantity: 7,
  },
  {
    label: 'Suco Pronto',
    value: 'suco-pronto',
    selected: false,
    quantity: 168,
  },
  {
    label: 'Suco Refrigerado',
    value: 'suco-refrigerado',
    selected: false,
    quantity: 29,
  },
  {
    label: 'Tequila',
    value: 'tequila',
    selected: false,
    quantity: 4,
  },
  {
    label: 'Tradicional',
    value: 'tradicional',
    selected: false,
    quantity: 158,
  },
  {
    label: 'Vinho Branco',
    value: 'vinho-branco',
    selected: false,
    quantity: 103,
  },
  {
    label: 'Vinho Rosé',
    value: 'vinho-rose',
    selected: false,
    quantity: 47,
  },
  {
    label: 'Vinho Tinto',
    value: 'vinho-tinto',
    selected: false,
    quantity: 332,
  },
  {
    label: 'Vodka',
    value: 'vodka',
    selected: false,
    quantity: 21,
  },
  {
    label: 'Whisky',
    value: 'whisky',
    selected: false,
    quantity: 57,
  },
]

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method
  }
}
