

###
GET http://localhost:3333



###
POST http://localhost:3333/user
Content-Type: application/json

{
    "email": "lucas@gmail.com",
    "name": "Evento Semana Formação.DEV",
    "password":"123123"
}


###
POST http://localhost:3333/auth
Content-Type: application/json

{
    "email": "lucas@gmail.com",
    "password":"123123"
}


###
GET http://localhost:3333/me
Content-Type: application/json
Authorization: Bearer oat_MQ.dmU3SjU1STd5SjE5QXNXQ3VMN3ZWWDRDWmZQS2NlOF9oanF1MnVmSTI0NzgwOTMxMTM



###
POST http://localhost:3333/product
Content-Type: application/json
Authorization: Bearer oat_MQ.dmU3SjU1STd5SjE5QXNXQ3VMN3ZWWDRDWmZQS2NlOF9oanF1MnVmSTI0NzgwOTMxMTM

{
  "name": "Notebook 2",
  "description": "Notebook novo para você",
  "price": 110.0,
  "image": "https://wmxpnlilkuedvwtzjwqo.supabase.co/storage/v1/object/public/images/products/5.png?t=2025-01-06T20%3A32%3A13.436Z",
  "stock":10,
  "marketId":1,
  "categoryId": 1
}

###
POST http://localhost:3333/address
Content-Type: application/json
Authorization: Bearer oat_MQ.QTFvaVlzeHFnSlBRdnk2WmVRZGpmbkN0X2R1N0xINzZZNnlkWkh3MzM1NTgyNDAwNjM

{
  "address": "J3ose Vicente Cardoso Filho",
  "complement":"aqefef",
  "city":"wefwefwef",
  "zipCode":"56517500",
  "neighborhood":"wefwefwef",
  "number":10,
  "uf":"PE"
}


###
POST http://localhost:3333/order
Content-Type: application/json
Authorization: Bearer oat_MQ.dmU3SjU1STd5SjE5QXNXQ3VMN3ZWWDRDWmZQS2NlOF9oanF1MnVmSTI0NzgwOTMxMTM

{
  "payment":"CREDIT_CARD",
  "idAddress": 1,
  "products": [
  {
    "id_product": 2,
    "quantity": 1
  },
  {
    "id_product": 3,
    "quantity": 1
  },
   {
    "id_product": 3,
    "quantity": 1
  }
]
}


###
GET http://localhost:3333/order-by-user
Content-Type: application/json
Authorization: Bearer oat_MQ.dmU3SjU1STd5SjE5QXNXQ3VMN3ZWWDRDWmZQS2NlOF9oanF1MnVmSTI0NzgwOTMxMTM

###
GET http://localhost:3333/product?page=1
Content-Type: application/json
Authorization: Bearer oat_MQ.dmU3SjU1STd5SjE5QXNXQ3VMN3ZWWDRDWmZQS2NlOF9oanF1MnVmSTI0NzgwOTMxMTM

###
GET http://localhost:3333/address-by-user
Content-Type: application/json
Authorization: Bearer oat_MQ.dmU3SjU1STd5SjE5QXNXQ3VMN3ZWWDRDWmZQS2NlOF9oanF1MnVmSTI0NzgwOTMxMTM

###
GET http://localhost:3333/api/category
Content-Type: application/json

###
POST http://localhost:3333/market
Content-Type: application/json
Authorization: Bearer oat_MQ.dmU3SjU1STd5SjE5QXNXQ3VMN3ZWWDRDWmZQS2NlOF9oanF1MnVmSTI0NzgwOTMxMTM

{
    "name": "Mercado Paes",
    "addressId":"1"
}
