

###
GET http://localhost:3333



###
POST http://localhost:3333/user
Content-Type: application/json

{
    "email": "lucas@gmail.com",
    "name": "Evento Semana Formação.DEV",
    "password":"123123"
}


###
POST http://localhost:3333/auth
Content-Type: application/json

{
    "email": "lucas@gmail.com",
    "password":"123123"
}


###
GET http://localhost:3333/me
Content-Type: application/json
Authorization: Bearer oat_MQ.eVVHLVNXQnBSSHdIdk5wdUV0bXBTRUJrQk9RTXdzdkxRVDV0OTgxMTE5OTgwMTM3Mg



###
POST http://localhost:3333/product
Content-Type: application/json
Authorization: Bearer oat_MQ.eVVHLVNXQnBSSHdIdk5wdUV0bXBTRUJrQk9RTXdzdkxRVDV0OTgxMTE5OTgwMTM3Mg

{
  "name": "Notebook 2",
  "description": "Notebook novo para você",
  "price": 110.0,
  "image": "https://wmxpnlilkuedvwtzjwqo.supabase.co/storage/v1/object/public/images/products/5.png?t=2025-01-06T20%3A32%3A13.436Z",
  "stock":10,
  "marketId":1,
  "categoryId": 1
}

###
POST http://localhost:3333/api/address
Content-Type: application/json
Authorization: Bearer oat_MQ.eVVHLVNXQnBSSHdIdk5wdUV0bXBTRUJrQk9RTXdzdkxRVDV0OTgxMTE5OTgwMTM3Mg

{
  "address": "J3ose Vicente Cardoso Filho",
  "complement":"aqefef",
  "city":"wefwefwef",
  "zipCode":"56517500",
  "neighborhood":"wefwefwef",
  "number":10,
  "uf":"PE"
}


###
POST http://localhost:3333/order
Content-Type: application/json
Authorization: Bearer oat_MQ.eVVHLVNXQnBSSHdIdk5wdUV0bXBTRUJrQk9RTXdzdkxRVDV0OTgxMTE5OTgwMTM3Mg

{
  "payment":"CREDIT_CARD",
  "idAddress": 1,
  "products": [
  {
    "id_product": 2,
    "quantity": 1
  },
  {
    "id_product": 3,
    "quantity": 1
  },
   {
    "id_product": 3,
    "quantity": 1
  }
]
}


###
GET http://localhost:3333/order-by-user
Content-Type: application/json
Authorization: Bearer oat_MQ.eVVHLVNXQnBSSHdIdk5wdUV0bXBTRUJrQk9RTXdzdkxRVDV0OTgxMTE5OTgwMTM3Mg

###
GET http://localhost:3333/product?page=2&limit=6
Content-Type: application/json
Authorization: Bearer oat_MQ.eVVHLVNXQnBSSHdIdk5wdUV0bXBTRUJrQk9RTXdzdkxRVDV0OTgxMTE5OTgwMTM3Mg

###
GET http://localhost:3333/api/address-by-user
Content-Type: application/json
Authorization: Bearer oat_Mg.aDFoYlg4R3dMYkpEQWpyUkFMN1puYW95ZlMyLS1POW1KZjB4MkoxdjIyNzAxODY3NQ

###
GET http://localhost:3333/api/category?page=1
Content-Type: application/json

###
POST http://localhost:3333/market
Content-Type: application/json
Authorization: Bearer oat_MQ.eVVHLVNXQnBSSHdIdk5wdUV0bXBTRUJrQk9RTXdzdkxRVDV0OTgxMTE5OTgwMTM3Mg

{
    "name": "Mercado Paes",
    "addressId":"1"
}


###
GET http://localhost:3333/product/baking-needs
Content-Type: application/json

